services:
  mysql:
    image: mysql:1.0.0
    environment:
      MYSQL_ROOT_PASSWORD: ExpenseApp@1
    networks:
      - mynetwork
    volumes:
      - mysql:/var/lib/mysql

  backend:
    image: backend:1.0.0
    networks:
      - mynetwork
    depends_on:
      - mysql

  frontend:
    image: frontend:1.0.0
    networks:
      - mynetwork
    ports:
      - "80:80"
    depends_on:
      - backend